website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import LoginForm, SignupForm, ResetPasswordRequestForm, ResetPasswordForm
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .email import send_password_reset_email

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember = form.remember.data

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user, remember=remember)
            flash('Logged in successfully!', category='success')
            return redirect(url_for('views.home'))
        flash('Incorrect email or password. Please try again.', category='error')
    return render_template("login.html", user=current_user, form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    form = SignupForm()

    if form.validate_on_submit():
        email = form.email.data
        first_name = form.first_name.data
        password = form.password1.data

        if User.query.filter_by(email=email).first():
            flash('Email already exists.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created! Proceed to login.', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user, form=form)

@auth.route('/reset-password-request', methods=['GET', 'POST'])
def reset_password_request():
    form = ResetPasswordRequestForm()

    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()

        if user:
            reset_password_token = user.get_reset_password_token(user.id)
            db.session.commit()

            send_password_reset_email(user)
            flash('An email with instructions to reset your password has been sent to your email.', category='info')
            return redirect(url_for('auth.login'))
        else:
            flash('Email not found. Please check the email address and try again.', category='error')

    return render_template('reset_password_request.html', user=current_user, form=form)

@auth.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm()

    if form.validate_on_submit():
        new_password = form.new_password.data
        confirm_password = form.confirm_password.data

        if new_password != confirm_password:
            flash('Passwords do not match. Please try again.', category='error')
        else:
            user = User.verify_reset_password_token(token)
            if user:
                hashed_password = generate_password_hash(new_password, method='sha256')
                user.password = hashed_password
                user.reset_password_token = None
                db.session.commit()
                flash('Your password has been reset successfully. You can now log in with your new password.', category='success')
                return redirect(url_for('auth.login'))  # Return a valid response here

            flash('Invalid or expired token. Please request a new password reset.', category='error')

    return render_template('reset_password.html', token=token, user=current_user, form=form)

website/views.py
from flask import Blueprint, render_template, request, flash
from flask_login import login_required, current_user
from . import db


views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)

# Frontend Questions
@views.route('/frontend-questions')
@login_required
def frontend_questions():
    # Add your code to retrieve and display frontend questions here
    return render_template("frontend_questions.html", user=current_user)

# Backend Questions
@views.route('/backend-questions')
@login_required
def backend_questions():
    # Add your code to retrieve and display backend questions here
    return render_template("backend_questions.html")

# DevOps Questions
@views.route('/devops-questions')
@login_required
def devops_questions():
    # Add your code to retrieve and display devops questions here
    return render_template("devops_questions.html")

# Online Assessment
@views.route('/start_mock_assessment')
@login_required
def start_mock_assessment():
    return render_template("start_mock_assessment")

# HTML Questions
@views.route('/html-questions')
@login_required
def html_questions():
    return render_template("html_questions.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </nav>

        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

      <div class="container">{% block content %} {% endblock %}</div>

        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
        ></script>
        <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
        ></script>
</body>
</html>

website/templates/frontend_questions.html
{% extends "base.html" %}
{% block title %}Frontend Puzzle{% endblock %}

{% block content %}
<div id="contentContainer">
    <div class="container">
        <h1>Frontend Puzzle</h1>
        <br>
        <h4>Prepare yourself. Start a practice assessment from a collection of real company questions.</h4>
        
        <div class="row">
        <!-- Online Assessment -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Online Assessment</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startOnlineAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="ONLINE ASSESSMENT">Start</button>
                </div>
            </div>
        </div>

        <!-- HTML Assessment -->
        <div class="col-md-4">
            <div id="questionsList"></div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">HTML Assessment</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startHtmlAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="HTML ASSESSMENT">Start</button>
                </div>
            </div>
        </div>

        <!-- CSS Assessment -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">CSS Assessment</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startCssAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="CSS ASSESSMENT">Start</button>
                </div>
            </div>
        </div>
    </div>

    <br>

    <div class="row">
        <!-- JavaScript Assessment -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">JavaScript Assessment</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startJavaScriptAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="JavaScript ASSESSMENT">Start</button>
                </div>
            </div>
        </div>

        <!-- Version Control System Assessment -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Version Control System</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startVcsAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="VCS ASSESSMENT">Start</button>
                </div>
            </div>
        </div>

        <!-- Frameworks Assessment -->
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Frameworks Assessment</h5>
                    <p class="card-text">Random question set from a real company.</p>
                    <br>
                    <br>
                    <button id="startFrameworksAssessmentButton" class="btn btn-primary" data-toggle="modal" data-target="#assessmentModal" data-content="Frameworks ASSESSMENT">Start</button>
                </div>
            </div>
        </div>
    </div>

        <!-- Modal -->
    <div class="modal fade" id="assessmentModal" tabindex="-1" role="dialog" aria-labelledby="assessmentModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="assessmentModalLabel">Start Assessment</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Content will be updated based on the assessment type -->
                    <h6 id="assessmentType">Read the instructions.</h6>
                    <ul>
                        <li>Each session will include up to 20 random questions.</li>
                        <li>You will have 20 minutes to complete all questions.</li>
                        <li>Once a mock assessment session begins, you cannot pause the timer.</li>
                        <li>The mock assessment session will end when you have successfully submitted a correct answer for each question, the allotted time has expired, or you end the session manually.</li>
                    </ul>
                    <p>Good Luck!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <!-- The URL will be updated dynamically based on the assessment type -->
                    <a id="startAssessmentLink" href="#" class="btn btn-primary">Start Mock Assessment</a>
                </div>
            </div>
        </div>
    </div>
    <script>
    let currentQuestionIndex = 0;
    let questions = []; // Define an array to store the questions

    document.addEventListener('DOMContentLoaded', function () {
        const startHtmlAssessmentButton = document.getElementById('startHtmlAssessmentButton');
        const startAssessmentLink = document.getElementById('startAssessmentLink');

        startHtmlAssessmentButton.addEventListener('click', function () {
            // Show the modal
            $('#assessmentModal').modal('show');
        });

        startAssessmentLink.addEventListener('click', function () {
            // Close the modal if needed
            $('#assessmentModal').modal('hide');

            // Fetch questions and replace the content
            fetchQuestionsAndReplaceContent();
        });
    });

    function nextQuestion() {
    const selectedAnswer = document.querySelector(`input[name="question_${currentQuestionIndex}"]:checked`);
    
    if (selectedAnswer) {
        // Save the user's answer (you can save it in an array or database)
        const answer = selectedAnswer.value;
        console.log(`User selected answer for question ${currentQuestionIndex}: ${answer}`);

        // Move to the next question
        currentQuestionIndex++;

        // Fetch questions and replace the content with the next question
        fetchQuestionsAndReplaceContent();
    } else {
        // Prompt the user to select an answer before moving to the next question
        alert('Please select an answer before moving to the next question.');
    }
}

    function renderNextQuestion(index) {
        // Check if there is a next question to render
        if (index < questions.length) {
            const nextQuestion = questions[index];
            const contentContainer = document.getElementById('contentContainer');

            // Generate HTML for the next question
            const questionHTML = generateQuestionHTML(nextQuestion, index);
            console.log('Next question HTML:', questionHTML); // Log the HTML generated for the next question

            // Replace the content with the next question
            contentContainer.innerHTML = questionHTML;
        }
    }

    function generateQuestionHTML(question, index) {
    let html = '<ul>';
    html += `<li>Question ${index + 1}: ${question.question_text}</li>`;
    html += '<ul type="A">';
    html += `<li><input type="radio" name="question_${index}" value="A"> A. ${question.option_A}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="B"> B. ${question.option_B}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="C"> C. ${question.option_C}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="D"> D. ${question.option_D}</li>`;
    html += `<button onclick="nextQuestion()">Next</button>`; // Add a "Next" button
    html += '</ul>';
    return html;
}

    // Function to fetch questions and replace the content
    function fetchQuestionsAndReplaceContent() {
        // Perform an HTTP request to fetch questions
        fetch('/api/questions') // Adjust the URL to match your backend endpoint
            .then((response) => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Error fetching questions');
                }
            })
            .then((data) => {
                console.log('Data received:', data); // Log the data

                questions = data; // Store the fetched questions in the array
                console.log('Current question index:', currentQuestionIndex); // Log the current question index
                renderNextQuestion(currentQuestionIndex); // Display the first question
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }
</script>
</div>
 
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Question Listing{% endblock %}

{% block content %}
<div class="container">
    <h1>Welcome to PuzzloCode!</h1>
    <h2>Explore your stack!</h2>
    <br>
    <br>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Frontend</h3>
                    <p>Explore coding questions for frontend development.</p>
                </div>
                <div class="card-footer">
                    <!-- Add a link to frontend questions -->
                    <a href="{{ url_for('views.frontend_questions') }}" class="btn btn-primary">Explore Frontend Questions</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Backend</h3>
                    <p>Explore coding questions for backend development.</p>
                </div>
                <div class="card-footer">
                    <!-- Add a link to backend questions -->
                    <a href="{{ url_for('views.backend_questions') }}" class="btn btn-primary">Explore Backend Questions</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>DevOps</h3>
                    <p>Explore coding questions for DevOps practices.</p>
                </div>
                <div class="card-footer">
                    <!-- Add a link to DevOps questions -->
                    <a href="{{ url_for('views.devops_questions') }}" class="btn btn-primary">Explore DevOps Questions</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/html-questions.html
{% extends "base.html" %}

{% block title %}HTML Assessment{% endblock %}

{% block content %}
<div id="questionContainer">
<script>
    let currentQuestionIndex = 0;
    let questions = []; // Define an array to store the questions

    document.addEventListener('DOMContentLoaded', function () {
        const startHtmlAssessmentButton = document.getElementById('startHtmlAssessmentButton');
        const startAssessmentLink = document.getElementById('startAssessmentLink');

        startHtmlAssessmentButton.addEventListener('click', function () {
            // Show the modal
            $('#assessmentModal').modal('show');
        });

        startAssessmentLink.addEventListener('click', function () {
            // Close the modal if needed
            $('#assessmentModal').modal('hide');

            // Fetch questions and replace the content
            fetchQuestionsAndReplaceContent();
        });
    });

    function nextQuestion() {
    const selectedAnswer = document.querySelector(`input[name="question_${currentQuestionIndex}"]:checked`);
    
    if (selectedAnswer) {
        // Save the user's answer (you can save it in an array or database)
        const answer = selectedAnswer.value;
        console.log(`User selected answer for question ${currentQuestionIndex}: ${answer}`);

        // Move to the next question
        currentQuestionIndex++;

        // Fetch questions and replace the content with the next question
        fetchQuestionsAndReplaceContent();
    } else {
        // Prompt the user to select an answer before moving to the next question
        alert('Please select an answer before moving to the next question.');
    }
}

    function renderNextQuestion(index) {
        // Check if there is a next question to render
        if (index < questions.length) {
            const nextQuestion = questions[index];
            const contentContainer = document.getElementById('contentContainer');

            // Generate HTML for the next question
            const questionHTML = generateQuestionHTML(nextQuestion, index);
            console.log('Next question HTML:', questionHTML); // Log the HTML generated for the next question

            // Replace the content with the next question
            contentContainer.innerHTML = questionHTML;
        }
    }

    function generateQuestionHTML(question, index) {
    let html = '<ul>';
    html += `<li>Question ${index + 1}: ${question.question_text}</li>`;
    html += '<ul type="A">';
    html += `<li><input type="radio" name="question_${index}" value="A"> A. ${question.option_A}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="B"> B. ${question.option_B}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="C"> C. ${question.option_C}</li>`;
    html += `<li><input type="radio" name="question_${index}" value="D"> D. ${question.option_D}</li>`;
    html += `<button onclick="nextQuestion()">Next</button>`; // Add a "Next" button
    html += '</ul>';
    return html;
}

    // Function to fetch questions and replace the content
    function fetchQuestionsAndReplaceContent() {
        // Perform an HTTP request to fetch questions
        fetch('/api/questions') // Adjust the URL to match your backend endpoint
            .then((response) => {
                if (response.ok) {
                    return response.json();
                } else {
                    throw new Error('Error fetching questions');
                }
            })
            .then((data) => {
                console.log('Data received:', data); // Log the data

                questions = data; // Store the fetched questions in the array
                console.log('Current question index:', currentQuestionIndex); // Log the current question index
                renderNextQuestion(currentQuestionIndex); // Display the first question
            })
            .catch((error) => {
                console.error('Error:', error);
            });
    }
</script>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
  <form method="POST">
    <h3 align="center">Login</h3>
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label(class="form-label") }}
      {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-label") }}
      {{ form.password(class="form-control") }}
    </div>
    <div class="form-check">
      {{ form.remember(class="form-check-input") }}
      {{ form.remember.label(class="form-check-label") }}
    </div>
    <br />
    {{ form.submit(class="btn btn-primary") }}
  </form>
  <p class="mt-3">
    <a href="{{ url_for('auth.reset_password_request') }}">Forgot your password?</a>
  </p>
{% endblock %}

website/templates/reset_password.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock %}

{% block content %}
  <h3 align="center">Reset Password</h3>
  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.new_password.label(class="form-label") }}
      {{ form.new_password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.confirm_password.label(class="form-label") }}
      {{ form.confirm_password(class="form-control") }}
    </div>
    <br />
    {{ form.submit(class="btn btn-primary") }}
  </form>
{% endblock %}

website/templates/reset_password_request.html
{% extends "base.html" %}
{% block title %}Reset Password Request{% endblock %}

{% block content %}
  <h3 align="center">Reset Password Request</h3>
  
  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label(class="form-label") }}
      {{ form.email(class="form-control") }}
    </div>
    <br />
    {{ form.submit(class="btn btn-primary") }}
  </form>
  
  <br />
  
  <p>
    <a href="{{ url_for('auth.login') }}">Back to Login</a>
  </p>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
  <form method="POST">
    <h3 align="center">Sign Up</h3>
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.email.label(class="form-label") }}
      {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.first_name.label(class="form-label") }}
      {{ form.first_name(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label(class="form-label") }}
      {{ form.password(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password1.label(class="form-label") }}
      {{ form.password1(class="form-control") }}
    </div>
    <br />
    {{ form.submit(class="btn btn-primary") }}
  </form>
{% endblock %}